# Generated by Django 3.1.1 on 2020-10-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200929_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_2',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
