# Generated by Django 3.1 on 2020-09-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=254, null=True)),
                ('confirmed', models.CharField(blank=True, max_length=254, null=True)),
                ('deaths', models.CharField(blank=True, max_length=254, null=True)),
                ('recovered', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
