# Generated by Django 3.1 on 2020-09-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country_stats',
        ),
    ]
