# Generated by Django 3.1 on 2020-09-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_stats',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
