# Generated by Django 3.1 on 2020-09-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_country_stats_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='country_stats',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
