# Generated by Django 3.1.1 on 2020-10-01 15:34

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_auto_20200929_1312'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('firstname', models.CharField(max_length=254, null=True)),
                ('lastname', models.CharField(max_length=254, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('address_1', models.CharField(max_length=1000, null=True)),
                ('address_2', models.CharField(default='', max_length=1000, null=True)),
                ('city', models.CharField(max_length=1000, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_bag.order')),
            ],
        ),
    ]
