# Generated by Django 3.1.1 on 2020-10-05 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0003_order_order_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_1',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_2',
            new_name='address_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
