# Generated by Django 3.1.1 on 2020-10-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0006_auto_20201006_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
