# Generated by Django 3.1.1 on 2020-10-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0007_order_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_dispatched',
            field=models.DateTimeField(null=True),
        ),
    ]
