# Generated by Django 3.1.1 on 2020-10-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_bag', '0008_order_date_dispatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_profile',
            new_name='customer_profile',
        ),
    ]
