# Generated by Django 3.1.1 on 2020-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('has_size', models.BooleanField(blank=True, default=False, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('number_in_stock', models.IntegerField(default=0, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('created_by', models.CharField(max_length=254, null=True)),
                ('created_date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
