# Generated by Django 3.1.1 on 2020-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200915_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_in_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
