# Generated by Django 3.1.1 on 2020-10-05 14:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201004_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/noimage.png', force_format=None, keep_meta=True, quality=0, size=[400, 500], upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/noimage.png', force_format=None, keep_meta=True, quality=0, size=[400, 500], upload_to='media/'),
        ),
    ]
