# Generated by Django 3.1.1 on 2020-10-07 15:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20201006_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='noimage.png', force_format=None, keep_meta=True, null=True, quality=100, size=[400, 500], upload_to=''),
        ),
    ]
