# Generated by Django 3.1.1 on 2020-10-13 21:08

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20201013_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='noimage.jpeg', force_format=None, keep_meta=True, quality=100, size=[400, 500], upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='noimage.jpeg', force_format=None, keep_meta=True, null=True, quality=100, size=[400, 500], upload_to=''),
        ),
    ]
